"""Replay smoke test — the live harness is exercised via ``polybench.replay``
against either a committed live fixture (if present) or a synthetic one
generated by ``conftest.py``. Confirms the full pipeline works end-to-end
without touching the network.
"""

from __future__ import annotations

import asyncio
import math
from pathlib import Path

from polybench import FLAT, Model, Side, Signal, Tick
from polybench.baselines import MomentumBaseline
from polybench.harness import Harness, HarnessConfig
from polybench.replay import ReplayConfig, replay


def _cfg(tmp_path: Path) -> ReplayConfig:
    return ReplayConfig(
        starting_capital=1000.0,
        slippage_bps=200.0,
        output_dir=tmp_path / "out",
        scratch_dir=tmp_path / "scratch",
    )


class _AlwaysUpModel(Model):
    """Test-only control: buys UP at size 1.0 every tick. Used to assert the
    replay path handles held-to-resolution PnL correctly."""

    def on_tick(self, tick: Tick) -> Signal | None:
        return Signal(side=Side.UP, size=1.0)


class _FlatModel(Model):
    def on_tick(self, tick: Tick) -> Signal | None:
        return FLAT


class _InvalidSignalModel(Model):
    def on_tick(self, tick: Tick) -> Signal | None:
        return Signal(side="BAD", size="not-a-number")  # type: ignore[arg-type]


class _RefreshCountingClient:
    def __init__(self) -> None:
        self.refresh_calls = 0

    async def refresh_event(self, slug: str):
        self.refresh_calls += 1
        return None


def _tick() -> Tick:
    return Tick(
        ts=1.0,
        time_to_resolve=10.0,
        btc_last=100.0,
        btc_bid=99.0,
        btc_ask=101.0,
        up_bid=0.49,
        up_ask=0.51,
        up_mid=0.50,
        down_bid=0.49,
        down_ask=0.51,
        down_mid=0.50,
    )


def test_replay_flat_model_zero_pnl(any_event_fixture: Path, tmp_path: Path) -> None:
    result = replay(_FlatModel(), any_event_fixture, _cfg(tmp_path))
    assert math.isfinite(result.pnl_total)
    assert result.metrics["n_events"] >= 1
    # FLAT never trades → pnl is 0.
    assert result.metrics["n_trades"] == 0
    # Dual-column: baseline should also be present.
    assert "primary_score" in result.baseline_metrics


def test_replay_always_up_produces_resolution_pnl(
    any_event_fixture: Path, tmp_path: Path
) -> None:
    result = replay(_AlwaysUpModel(), any_event_fixture, _cfg(tmp_path))
    reso = result.metrics["pnl_resolution"]
    # AlwaysUp holds through resolution, so the replay path must attribute
    # some PnL to settlement rather than treating the event as mark-only.
    assert abs(reso) > 0.0


def test_replay_momentum_baseline_runs(
    any_event_fixture: Path, tmp_path: Path
) -> None:
    result = replay(
        MomentumBaseline(config={"threshold_bps": 1.0}),
        any_event_fixture,
        _cfg(tmp_path),
    )
    assert math.isfinite(result.pnl_total)
    assert result.metrics["n_events"] >= 1


def test_momentum_baseline_uses_up_mid_when_btc_unavailable() -> None:
    model = MomentumBaseline(config={"lookback_s": 2, "pm_threshold": 0.01})
    tick = Tick(
        ts=1.0,
        time_to_resolve=100.0,
        btc_last=0.0,
        btc_bid=0.0,
        btc_ask=0.0,
        up_bid=0.52,
        up_ask=0.54,
        up_mid=0.53,
        down_bid=0.46,
        down_ask=0.48,
        down_mid=0.47,
        btc_recent=(),
        up_mid_recent=(0.50, 0.51, 0.53),
    )
    signal = model.on_tick(tick)
    assert signal is not None
    assert signal.side == Side.UP
    assert signal.size > 0.0


def test_replay_writes_dual_column_report_json(
    any_event_fixture: Path, tmp_path: Path
) -> None:
    cfg = _cfg(tmp_path)
    replay(_FlatModel(), any_event_fixture, cfg)
    import json
    report_path = cfg.output_dir / "report.json"
    assert report_path.is_file()
    payload = json.loads(report_path.read_text())
    # New schema: model + baseline dicts.
    assert "model" in payload
    assert "baseline" in payload
    assert "metrics" in payload["model"]
    assert "metrics" in payload["baseline"]


def test_live_harness_drops_invalid_signal(tmp_path: Path) -> None:
    harness = Harness(_InvalidSignalModel(), HarnessConfig(output_dir=tmp_path / "out"))
    try:
        assert harness._safe_on_tick(_InvalidSignalModel(), _tick()) is None
    finally:
        harness._executor.shutdown(wait=False, cancel_futures=True)


def test_postmortem_resolution_disabled_skips_gamma_refresh(tmp_path: Path) -> None:
    client = _RefreshCountingClient()
    harness = Harness(
        _FlatModel(),
        HarnessConfig(output_dir=tmp_path / "out", postmortem_resolution_s=0.0),
        client=client,  # type: ignore[arg-type]
    )
    try:
        for simulator in (harness._simulator, harness._baseline_simulator):
            simulator.start_event("E1", "btc-updown-test", 0.0, 0.5, 0.5)
            simulator.finish_event(1.0, None, None)

        asyncio.run(harness._postmortem_resolve_unknowns(max_wait_s=0.0, poll_interval_s=0.0))
        assert client.refresh_calls == 0
    finally:
        harness._executor.shutdown(wait=False, cancel_futures=True)
