"""Replay smoke test — the live harness is exercised via ``polybench.replay``
against either a committed live fixture (if present) or a synthetic one
generated by ``conftest.py``. Confirms the full pipeline works end-to-end
without touching the network.
"""

from __future__ import annotations

import math
from pathlib import Path

from polybench.baselines import AlwaysUpModel, MomentumBaseline, RandomModel
from polybench.replay import ReplayConfig, replay


def _cfg(tmp_path: Path) -> ReplayConfig:
    return ReplayConfig(
        starting_capital=1000.0,
        slippage_bps=200.0,
        output_dir=tmp_path / "out",
        scratch_dir=tmp_path / "scratch",
    )


def test_replay_random_model(any_event_fixture: Path, tmp_path: Path) -> None:
    result = replay(RandomModel(config={"seed": 1}), any_event_fixture, _cfg(tmp_path))
    assert math.isfinite(result.pnl_total)
    assert math.isfinite(result.metrics["sharpe"])
    assert result.metrics["n_events"] >= 1
    assert result.metrics["n_ticks"] >= 1


def test_replay_alwaysup_produces_resolution_pnl(
    any_event_fixture: Path, tmp_path: Path
) -> None:
    result = replay(AlwaysUpModel(), any_event_fixture, _cfg(tmp_path))
    # AlwaysUp holds through resolution on every event, so resolution PnL
    # must dominate intra-event PnL.
    intra = result.metrics["pnl_intra_event"]
    reso = result.metrics["pnl_resolution"]
    assert abs(reso) >= abs(intra)


def test_replay_momentum_baseline_runs(
    any_event_fixture: Path, tmp_path: Path
) -> None:
    result = replay(
        MomentumBaseline(config={"threshold_bps": 1.0}),
        any_event_fixture,
        _cfg(tmp_path),
    )
    assert math.isfinite(result.pnl_total)
    assert result.metrics["n_events"] >= 1


def test_replay_writes_report_json(any_event_fixture: Path, tmp_path: Path) -> None:
    cfg = _cfg(tmp_path)
    replay(RandomModel(config={"seed": 0}), any_event_fixture, cfg)
    report_path = cfg.output_dir / "report.json"
    assert report_path.is_file()
    assert report_path.stat().st_size > 0
